# coding: utf-8

# flake8: noqa

"""
    QQAPP API

    QQAPP API Description  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.abrsm_composition_api import AbrsmCompositionApi
from swagger_client.api.abrsm_exam_api import AbrsmExamApi
from swagger_client.api.abrsm_order_api import AbrsmOrderApi
from swagger_client.api.abrsm_performance_api import AbrsmPerformanceApi
from swagger_client.api.abrsm_suite_api import AbrsmSuiteApi
from swagger_client.api.class_session_api import ClassSessionApi
from swagger_client.api.client_api import ClientApi
from swagger_client.api.course_api import CourseApi
from swagger_client.api.income_api import IncomeApi
from swagger_client.api.lesson_op_api import LessonOpApi
from swagger_client.api.video_api import VideoApi
# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.class_session import ClassSession
from swagger_client.models.class_session_list import ClassSessionList
from swagger_client.models.client import Client
from swagger_client.models.composition import Composition
from swagger_client.models.course import Course
from swagger_client.models.course_list import CourseList
from swagger_client.models.exam import Exam
from swagger_client.models.income import Income
from swagger_client.models.inline_response200 import InlineResponse200
from swagger_client.models.inline_response2001 import InlineResponse2001
from swagger_client.models.inline_response20010 import InlineResponse20010
from swagger_client.models.inline_response2002 import InlineResponse2002
from swagger_client.models.inline_response2003 import InlineResponse2003
from swagger_client.models.inline_response2004 import InlineResponse2004
from swagger_client.models.inline_response2005 import InlineResponse2005
from swagger_client.models.inline_response2006 import InlineResponse2006
from swagger_client.models.inline_response2007 import InlineResponse2007
from swagger_client.models.inline_response2008 import InlineResponse2008
from swagger_client.models.inline_response2009 import InlineResponse2009
from swagger_client.models.lesson_op_log import LessonOpLog
from swagger_client.models.lesson_op_log_list import LessonOpLogList
from swagger_client.models.order import Order
from swagger_client.models.performance import Performance
from swagger_client.models.suite import Suite
from swagger_client.models.video import Video
