# coding: utf-8

"""
    QQAPP API

    QQAPP API Description  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LessonOpLog(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'lessons': 'int',
        'create_time': 'datetime',
        'update_time': 'datetime',
        'op_type': 'int',
        'course': 'str'
    }

    attribute_map = {
        'id': 'id',
        'lessons': 'lessons',
        'create_time': 'create_time',
        'update_time': 'update_time',
        'op_type': 'op_type',
        'course': 'course'
    }

    def __init__(self, id=None, lessons=None, create_time=None, update_time=None, op_type=None, course=None):  # noqa: E501
        """LessonOpLog - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._lessons = None
        self._create_time = None
        self._update_time = None
        self._op_type = None
        self._course = None
        self.discriminator = None
        if id is not None:
            self.id = id
        self.lessons = lessons
        if create_time is not None:
            self.create_time = create_time
        if update_time is not None:
            self.update_time = update_time
        self.op_type = op_type
        self.course = course

    @property
    def id(self):
        """Gets the id of this LessonOpLog.  # noqa: E501


        :return: The id of this LessonOpLog.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this LessonOpLog.


        :param id: The id of this LessonOpLog.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def lessons(self):
        """Gets the lessons of this LessonOpLog.  # noqa: E501


        :return: The lessons of this LessonOpLog.  # noqa: E501
        :rtype: int
        """
        return self._lessons

    @lessons.setter
    def lessons(self, lessons):
        """Sets the lessons of this LessonOpLog.


        :param lessons: The lessons of this LessonOpLog.  # noqa: E501
        :type: int
        """
        if lessons is None:
            raise ValueError("Invalid value for `lessons`, must not be `None`")  # noqa: E501

        self._lessons = lessons

    @property
    def create_time(self):
        """Gets the create_time of this LessonOpLog.  # noqa: E501


        :return: The create_time of this LessonOpLog.  # noqa: E501
        :rtype: datetime
        """
        return self._create_time

    @create_time.setter
    def create_time(self, create_time):
        """Sets the create_time of this LessonOpLog.


        :param create_time: The create_time of this LessonOpLog.  # noqa: E501
        :type: datetime
        """

        self._create_time = create_time

    @property
    def update_time(self):
        """Gets the update_time of this LessonOpLog.  # noqa: E501


        :return: The update_time of this LessonOpLog.  # noqa: E501
        :rtype: datetime
        """
        return self._update_time

    @update_time.setter
    def update_time(self, update_time):
        """Sets the update_time of this LessonOpLog.


        :param update_time: The update_time of this LessonOpLog.  # noqa: E501
        :type: datetime
        """

        self._update_time = update_time

    @property
    def op_type(self):
        """Gets the op_type of this LessonOpLog.  # noqa: E501


        :return: The op_type of this LessonOpLog.  # noqa: E501
        :rtype: int
        """
        return self._op_type

    @op_type.setter
    def op_type(self, op_type):
        """Sets the op_type of this LessonOpLog.


        :param op_type: The op_type of this LessonOpLog.  # noqa: E501
        :type: int
        """
        if op_type is None:
            raise ValueError("Invalid value for `op_type`, must not be `None`")  # noqa: E501

        self._op_type = op_type

    @property
    def course(self):
        """Gets the course of this LessonOpLog.  # noqa: E501


        :return: The course of this LessonOpLog.  # noqa: E501
        :rtype: str
        """
        return self._course

    @course.setter
    def course(self, course):
        """Sets the course of this LessonOpLog.


        :param course: The course of this LessonOpLog.  # noqa: E501
        :type: str
        """
        if course is None:
            raise ValueError("Invalid value for `course`, must not be `None`")  # noqa: E501

        self._course = course

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LessonOpLog, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LessonOpLog):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
