# coding: utf-8

"""
    QQAPP API

    QQAPP API Description  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.abrsm_exam_api import AbrsmExamApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAbrsmExamApi(unittest.TestCase):
    """AbrsmExamApi unit test stubs"""

    def setUp(self):
        self.api = AbrsmExamApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_abrsm_exam_create(self):
        """Test case for abrsm_exam_create

        """
        pass

    def test_abrsm_exam_delete(self):
        """Test case for abrsm_exam_delete

        """
        pass

    def test_abrsm_exam_list(self):
        """Test case for abrsm_exam_list

        """
        pass

    def test_abrsm_exam_partial_update(self):
        """Test case for abrsm_exam_partial_update

        """
        pass

    def test_abrsm_exam_read(self):
        """Test case for abrsm_exam_read

        """
        pass

    def test_abrsm_exam_update(self):
        """Test case for abrsm_exam_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
