# coding: utf-8

"""
    QQAPP API

    QQAPP API Description  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.class_session_api import ClassSessionApi  # noqa: E501
from swagger_client.rest import ApiException


class TestClassSessionApi(unittest.TestCase):
    """ClassSessionApi unit test stubs"""

    def setUp(self):
        self.api = ClassSessionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_class_session_create(self):
        """Test case for class_session_create

        """
        pass

    def test_class_session_delete(self):
        """Test case for class_session_delete

        """
        pass

    def test_class_session_list(self):
        """Test case for class_session_list

        """
        pass

    def test_class_session_partial_update(self):
        """Test case for class_session_partial_update

        """
        pass

    def test_class_session_read(self):
        """Test case for class_session_read

        """
        pass

    def test_class_session_update(self):
        """Test case for class_session_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
