# coding: utf-8

"""
    QQAPP API

    QQAPP API Description  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.client import Client  # noqa: E501
from swagger_client.rest import ApiException


class TestClient(unittest.TestCase):
    """Client unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClient(self):
        """Test Client"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.client.Client()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
