# coding: utf-8

"""
    QQAPP API

    QQAPP API Description  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.abrsm_suite_api import AbrsmSuiteApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAbrsmSuiteApi(unittest.TestCase):
    """AbrsmSuiteApi unit test stubs"""

    def setUp(self):
        self.api = AbrsmSuiteApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_abrsm_suite_create(self):
        """Test case for abrsm_suite_create

        """
        pass

    def test_abrsm_suite_delete(self):
        """Test case for abrsm_suite_delete

        """
        pass

    def test_abrsm_suite_list(self):
        """Test case for abrsm_suite_list

        """
        pass

    def test_abrsm_suite_partial_update(self):
        """Test case for abrsm_suite_partial_update

        """
        pass

    def test_abrsm_suite_read(self):
        """Test case for abrsm_suite_read

        """
        pass

    def test_abrsm_suite_update(self):
        """Test case for abrsm_suite_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
