# coding: utf-8

"""
    QQAPP API

    QQAPP API Description  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.course_api import CourseApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCourseApi(unittest.TestCase):
    """CourseApi unit test stubs"""

    def setUp(self):
        self.api = CourseApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_course_create(self):
        """Test case for course_create

        """
        pass

    def test_course_delete(self):
        """Test case for course_delete

        """
        pass

    def test_course_list(self):
        """Test case for course_list

        """
        pass

    def test_course_partial_update(self):
        """Test case for course_partial_update

        """
        pass

    def test_course_read(self):
        """Test case for course_read

        """
        pass

    def test_course_update(self):
        """Test case for course_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
