# coding: utf-8

"""
    QQAPP API

    QQAPP API Description  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.income_api import IncomeApi  # noqa: E501
from swagger_client.rest import ApiException


class TestIncomeApi(unittest.TestCase):
    """IncomeApi unit test stubs"""

    def setUp(self):
        self.api = IncomeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_income_create(self):
        """Test case for income_create

        """
        pass

    def test_income_delete(self):
        """Test case for income_delete

        """
        pass

    def test_income_list(self):
        """Test case for income_list

        """
        pass

    def test_income_partial_update(self):
        """Test case for income_partial_update

        """
        pass

    def test_income_read(self):
        """Test case for income_read

        """
        pass

    def test_income_update(self):
        """Test case for income_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
