# coding: utf-8

"""
    QQAPP API

    QQAPP API Description  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.video_api import VideoApi  # noqa: E501
from swagger_client.rest import ApiException


class TestVideoApi(unittest.TestCase):
    """VideoApi unit test stubs"""

    def setUp(self):
        self.api = VideoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_video_create(self):
        """Test case for video_create

        """
        pass

    def test_video_delete(self):
        """Test case for video_delete

        """
        pass

    def test_video_list(self):
        """Test case for video_list

        """
        pass

    def test_video_partial_update(self):
        """Test case for video_partial_update

        """
        pass

    def test_video_read(self):
        """Test case for video_read

        """
        pass

    def test_video_update(self):
        """Test case for video_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
