# coding: utf-8

"""
    QQAPP API

    QQAPP API Description  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.composition import Composition  # noqa: E501
from swagger_client.rest import ApiException


class TestComposition(unittest.TestCase):
    """Composition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComposition(self):
        """Test Composition"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.composition.Composition()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
