# coding: utf-8

"""
    QQAPP API

    QQAPP API Description  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.abrsm_performance_api import AbrsmPerformanceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAbrsmPerformanceApi(unittest.TestCase):
    """AbrsmPerformanceApi unit test stubs"""

    def setUp(self):
        self.api = AbrsmPerformanceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_abrsm_performance_create(self):
        """Test case for abrsm_performance_create

        """
        pass

    def test_abrsm_performance_delete(self):
        """Test case for abrsm_performance_delete

        """
        pass

    def test_abrsm_performance_list(self):
        """Test case for abrsm_performance_list

        """
        pass

    def test_abrsm_performance_partial_update(self):
        """Test case for abrsm_performance_partial_update

        """
        pass

    def test_abrsm_performance_read(self):
        """Test case for abrsm_performance_read

        """
        pass

    def test_abrsm_performance_update(self):
        """Test case for abrsm_performance_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
