# coding: utf-8

"""
    QQAPP API

    QQAPP API Description  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.lesson_op_api import LessonOpApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLessonOpApi(unittest.TestCase):
    """LessonOpApi unit test stubs"""

    def setUp(self):
        self.api = LessonOpApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_lesson_op_create(self):
        """Test case for lesson_op_create

        """
        pass

    def test_lesson_op_list(self):
        """Test case for lesson_op_list

        """
        pass

    def test_lesson_op_read(self):
        """Test case for lesson_op_read

        """
        pass


if __name__ == '__main__':
    unittest.main()
