# coding: utf-8

"""
    QQAPP API

    QQAPP API Description  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.class_session_list import ClassSessionList  # noqa: E501
from swagger_client.rest import ApiException


class TestClassSessionList(unittest.TestCase):
    """ClassSessionList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClassSessionList(self):
        """Test ClassSessionList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.class_session_list.ClassSessionList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
