# coding: utf-8

"""
    QQAPP API

    QQAPP API Description  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.abrsm_order_api import AbrsmOrderApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAbrsmOrderApi(unittest.TestCase):
    """AbrsmOrderApi unit test stubs"""

    def setUp(self):
        self.api = AbrsmOrderApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_abrsm_order_create(self):
        """Test case for abrsm_order_create

        """
        pass

    def test_abrsm_order_delete(self):
        """Test case for abrsm_order_delete

        """
        pass

    def test_abrsm_order_list(self):
        """Test case for abrsm_order_list

        """
        pass

    def test_abrsm_order_partial_update(self):
        """Test case for abrsm_order_partial_update

        """
        pass

    def test_abrsm_order_read(self):
        """Test case for abrsm_order_read

        """
        pass

    def test_abrsm_order_update(self):
        """Test case for abrsm_order_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
