# coding: utf-8

"""
    QQAPP API

    QQAPP API Description  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.abrsm_composition_api import AbrsmCompositionApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAbrsmCompositionApi(unittest.TestCase):
    """AbrsmCompositionApi unit test stubs"""

    def setUp(self):
        self.api = AbrsmCompositionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_abrsm_composition_create(self):
        """Test case for abrsm_composition_create

        """
        pass

    def test_abrsm_composition_delete(self):
        """Test case for abrsm_composition_delete

        """
        pass

    def test_abrsm_composition_list(self):
        """Test case for abrsm_composition_list

        """
        pass

    def test_abrsm_composition_partial_update(self):
        """Test case for abrsm_composition_partial_update

        """
        pass

    def test_abrsm_composition_read(self):
        """Test case for abrsm_composition_read

        """
        pass

    def test_abrsm_composition_update(self):
        """Test case for abrsm_composition_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
