# coding: utf-8

"""
    QQAPP API

    QQAPP API Description  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.client_api import ClientApi  # noqa: E501
from swagger_client.rest import ApiException


class TestClientApi(unittest.TestCase):
    """ClientApi unit test stubs"""

    def setUp(self):
        self.api = ClientApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_client_create(self):
        """Test case for client_create

        """
        pass

    def test_client_delete(self):
        """Test case for client_delete

        """
        pass

    def test_client_list(self):
        """Test case for client_list

        """
        pass

    def test_client_partial_update(self):
        """Test case for client_partial_update

        """
        pass

    def test_client_read(self):
        """Test case for client_read

        """
        pass

    def test_client_update(self):
        """Test case for client_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
